### ISSUE TITLE
Lua torch line plot with multi lines fails during append

### ISSUE THREAD

**Issue by SelvamArul** [facebookresearch/visdom#117]
The follwing snippet 
```
th = require 'torch'
local visdom = require 'visdom'
plot = visdom{server = 'http://localhost', port = 8097, ipv6=false}

local id = plot:line{
   Y = torch.cat(torch.Tensor({0}), torch.Tensor({0}), 2),
   X = torch.cat(torch.Tensor({0}), torch.Tensor({0}), 2),
   options = {markers = false}
}
plot:line{
   Y = torch.cat(torch.Tensor({100}), torch.Tensor({100}), 2),
   X = torch.cat(torch.Tensor({100}), torch.Tensor({20}), 2),
   win = id,
   update = 'append',
}
```

fails with the follwing error message in visdom console:

```
ERROR:tornado.application:Uncaught exception POST /update (10.7.7.13)
HTTPServerRequest(protocol='http', host='localhost', method='POST', uri='/update', version='HTTP/1.1', remote_ip='10.7.7.13', headers={'Te': 'trailers', 'Host': 'localhost', 'Connection': 'close, TE', 'User-Agent': 'LuaSocket 3.0-rc1', 'Content-Length': '95', 'Content-Type': 'application/text'})
Traceback (most recent call last):
  File "/opt/python3.5/lib/python3.5/site-packages/tornado/web.py", line 1509, in _execute
    result = method(*self.path_args, **self.path_kwargs)
  File "/opt/python3.5/lib/python3.5/site-packages/visdom/server.py", line 314, in post
    p = self.update(p, args)
  File "/opt/python3.5/lib/python3.5/site-packages/visdom/server.py", line 290, in update
    if all([math.isnan(i) or i is None for i in new_data['x'][n]]):
IndexError: list index out of range
ERROR:root:ERROR: 500: {'exc_info': (<class 'IndexError'>, IndexError('list index out of range',), <traceback object at 0x7fcdfa5cea88>)}
```

This happens only when I create a Torch tensor from a Lua table of size 1. This following construct works

```
 Y = torch.cat(torch.Tensor({90,100}), torch.Tensor({90,100}), 2),
 X = torch.cat(torch.Tensor({90,100}), torch.Tensor({90,20}), 2),
```

**Comment by lvdmaaten** [comment]
Thanks for reporting! I will send out a fix soon.
