### ISSUE TITLE
Doesn't work with matplotlib

### ISSUE THREAD

**Issue by ysaatchi** [facebookresearch/visdom#119]
I would love it if I could easily send and update pylab plots within a pane. I can't see an easy way to do it right now.

**Comment by ajabri** [comment]
Hi @ysaatchi,

You're right, there is currently no support for reactive plots with matplot lib. This would be good to have. It may be easy to do with something like this: https://github.com/plotly/plotly.py/blob/master/plotly/offline/offline.py#L540 .

Alternatively, for now, you can just use `vis.image` with images of your mpl plots.

**Comment by ysaatchi** [comment]
Ah yes, that's a cool work around with vis.image :) I'm guessing it doesn't support sending a png directly, you have to save to png, then reload into an array.

**Comment by ajabri** [comment]
```
import matplotlib.pyplot as plt
import plotly.tools as tls

mpl_fig = plt.figure()
# --> your matplotlib methods <--

plotly_fig = tls.mpl_to_plotly(mpl_fig)
```

Then one can use `vis._send` as in https://github.com/facebookresearch/visdom/blob/master/py/__init__.py#L585 to send a request using plotly_fig's `data` and `layout`.

**Comment by dendisuhubdy** [comment]
@ajabri Tried this but it didn't work, I got this error

```
/u/suhubdyd/.conda/envs/dev3/lib/python3.6/site-packages/plotly/matplotlylib/renderer.py:396: UserWarning:

Aw. Snap! You're gonna have to hold off on the selfies for now. Plotly can't import images from matplotlib yet!

Traceback (most recent call last):
  File "ccw1-trainstats/pytorch/vgg/main.py", line 50, in <module>
    main()
  File "ccw1-trainstats/pytorch/vgg/main.py", line 46, in main
    layout=plotly_fig.layout,
TypeError: _send() got an unexpected keyword argument 'data'
```


```
import torch
import torchvision.models as models
import matplotlib
import matplotlib.pyplot as plt
import plotly.tools as tls

from visdom import Visdom


viz = Visdom(server='http://127.0.0.1', port = 51401)

def main():
    vgg = models.vgg16(pretrained=True)
    mm = vgg.double()
    filters = mm.modules
    body_model = [i for i in mm.children()][0]
    layer1 = body_model[0]
    tensor = layer1.weight.data.numpy()

    num_cols=6

    if not tensor.ndim==4:
        raise Exception("assumes a 4D tensor")
    if not tensor.shape[-1]==3:
        raise Exception("last dim needs to be 3 to plot")
    num_kernels = tensor.shape[0]
    num_rows = 1+ num_kernels // num_cols

    # starting the figure here

    fig = plt.figure(figsize=(num_cols,num_rows))
    for i in range(tensor.shape[0]):
        ax1 = fig.add_subplot(num_rows,num_cols,i+1)
        ax1.imshow(tensor[i])
        ax1.axis('off')
        ax1.set_xticklabels([])
        ax1.set_yticklabels([])

    plt.subplots_adjust(wspace=0.1, hspace=0.1)

    # plt.show()

    #plotly_fig = tls.mpl_to_plotly(fig)
    viz._send(
            data=plotly_fig.data,
            layout=plotly_fig.layout,
            )

if __name__=="__main__":
    main()
```

**Comment by ajabri** [comment]
You need to wrap the arguments you give to _send as a `dict`.

```
viz._send({
       data=plotly_fig.data,
       layout=plotly_fig.layout,
})
```

**Comment by dendisuhubdy** [comment]
@ajabri thanks!

**Comment by jbaron** [comment]
Although the solution below is not as nice as plotly graphs, there are cases when plotly cannot convert Matplotlib figures. An alternative might then to use SVG:

```
imgdata = io.StringIO()
fig.savefig(imgdata, format='svg')

svg_str= imgdata.getvalue()

# Make sure we can scale the SVG in Visdom
svg_str = re.sub('width=".*pt"', 'width="100%"', svg_str)
svg_str = re.sub('height=".*pt"', 'height="100%"', svg_str)

viz.svg(svg_str);
```

**Comment by JackUrb** [comment]
@jbaron Thanks for the tip - do you have any context for when plotly will fail to convert a Matplotlib figure? I'm hoping to add some support directly in the visdom side for Matplotlib soon (so that users have an easier way to interface between the two) and it would be useful to know how to distinguish.

**Comment by ayayayayayayayaay** [comment]
I am interested to fix this issue. I request you to allow me to fix it. can you assign me this issue

**Comment by Manik-Khajuria-5** [comment]
Matplot is already implemented in visdom
