### ISSUE TITLE
Address already in use

### ISSUE THREAD

**Issue by wj926** [facebookresearch/visdom#132]
I opened port 8097 and installed visdom in python3.6, then I typed 
python -m visdom.server 
however error message "Address already in use" came out 
How can I solve this problem. 
In this status when I go to http://localhost.com:8097, nothing comes out. 

Here are the error messages. 

(pytorch) tako@b7079:~$ python -m visdom.server
It's Alive!
Traceback (most recent call last):
  File "/home/tako/anaconda3/envs/pytorch/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/tako/anaconda3/envs/pytorch/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/tako/anaconda3/envs/pytorch/lib/python3.6/site-packages/visdom/server.py", line 438, in <module>
    main()
  File "/home/tako/anaconda3/envs/pytorch/lib/python3.6/site-packages/visdom/server.py", line 432, in main
    app.listen(FLAGS.port, max_buffer_size=1024 ** 3)
  File "/home/tako/anaconda3/envs/pytorch/lib/python3.6/site-packages/tornado/web.py", line 1943, in listen
    server.listen(port, address)
  File "/home/tako/anaconda3/envs/pytorch/lib/python3.6/site-packages/tornado/tcpserver.py", line 142, in listen
    sockets = bind_sockets(port, address=address)
  File "/home/tako/anaconda3/envs/pytorch/lib/python3.6/site-packages/tornado/netutil.py", line 197, in bind_sockets
    sock.bind(sockaddr)
OSError: [Errno 98] Address already in us

**Comment by ajabri** [comment]
HI @wj926 

What do you mean by you 'opened port 8097'? That message means that that port is being used by another e.g. socket. This can also happen if you incorrectly kill a socket that was once on 8097.

**Comment by wj926** [comment]
Hello @ajabri 
I mean that I allowed the port 8097 in /etc/ssh/sshd_config
I added "Port 8097" there

**Comment by ajabri** [comment]
Have you tried using a different port, e.g. 8098? You should not need to add the port to you sshd_config by the way.

**Comment by lvdmaaten** [comment]
Are you sure there isn't another concurrent visdom process still running that is blocking the port? Closing this since it does not appear to be a visdom issue.

**Comment by squirrel16** [comment]
hi, you can try another port like this `python -m visdom.server -p 8098` , and move to http://localhost:8098

**Comment by Feiyu-Zhang** [comment]
> Are you sure there isn't another concurrent visdom process still running that is blocking the port? Closing this since it does not appear to be a visdom issue.

Could multiple visdom processes with different port number run on one server node?

**Comment by JackUrb** [comment]
@Feiyu-Zhang yes, in fact this is a common configuration that we use.
