### ISSUE TITLE
Fails to launch demo.py

### ISSUE THREAD

**Issue by plumdeq** [facebookresearch/visdom#165]
It appears that I cannot properly run the provided `examples/demo.py`, below is the dump of my shell window. I am using the version available via `pip`.

```bash
Skipped video example
Exception in user code:
------------------------------------------------------------
Traceback (most recent call last):
  File "/home/asan/.Virtualenvs/sciprog/lib/python3.5/site-packages/visdom/__init__.py", line 240, in _send
    data=json.dumps(msg),
  File "/usr/lib/python3.5/json/__init__.py", line 230, in dumps
    return _default_encoder.encode(obj)
  File "/usr/lib/python3.5/json/encoder.py", line 198, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.5/json/encoder.py", line 256, in iterencode
    return _iterencode(o, 0)
TypeError: keys must be a string
Exception in user code:
------------------------------------------------------------
Traceback (most recent call last):
  File "/home/asan/.Virtualenvs/sciprog/lib/python3.5/site-packages/visdom/__init__.py", line 240, in _send
    data=json.dumps(msg),
  File "/usr/lib/python3.5/json/__init__.py", line 230, in dumps
    return _default_encoder.encode(obj)
  File "/usr/lib/python3.5/json/encoder.py", line 198, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.5/json/encoder.py", line 256, in iterencode
    return _iterencode(o, 0)
TypeError: keys must be a string
Traceback (most recent call last):
  File "demo.py", line 115, in <module>
    assert viz.win_exists(win)
AttributeError: 'Visdom' object has no attribute 'win_exists'
```

**Comment by lvdmaaten** [comment]
The demo you're running is for a visdom version that is newer than the current pip version. Please run the demo that comes with the pip version, or do a visdom install from source using `pip -e`.

We will be updating the pip version of visdom shortly.
