### ISSUE TITLE
stucked when start server

### ISSUE THREAD

**Issue by lpplbiubiubiub** [facebookresearch/visdom#184]
When I start server use "python -m visdom.server", I found the code is stucked and there is no response.  I terminated  this and got this:
`File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/local/lib/python2.7/dist-packages/visdom-0.1.6.1-py2.7.egg/visdom/server.py", line 636, in <module>
    download_scripts()
  File "/usr/local/lib/python2.7/dist-packages/visdom-0.1.6.1-py2.7.egg/visdom/server.py", line 615, in download_scrips
    data = opener.open(req).read()
  File "/usr/lib/python2.7/urllib2.py", line 404, in open
    response = self._open(req, data)
  File "/usr/lib/python2.7/urllib2.py", line 422, in _open
    '_open', req)
  File "/usr/lib/python2.7/urllib2.py", line 382, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 1222, in https_open
    return self.do_open(httplib.HTTPSConnection, req)
  File "/usr/lib/python2.7/urllib2.py", line 1181, in do_open
    h.request(req.get_method(), req.get_selector(), req.data, headers)
  File "/usr/lib/python2.7/httplib.py", line 1017, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python2.7/httplib.py", line 1051, in _send_request
    self.endheaders(body)
  File "/usr/lib/python2.7/httplib.py", line 1013, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 864, in _send_output
    self.send(msg)
  File "/usr/lib/python2.7/httplib.py", line 826, in send
    self.connect()
  File "/usr/lib/python2.7/httplib.py", line 1216, in connect
    self.timeout, self.source_address)
  File "/usr/lib/python2.7/socket.py", line 562, in create_connection
    sock.connect(sa)
  File "/usr/lib/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
KeyboardInterrupt
`
if I don't terminate this program, finally got this
`
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/local/lib/python2.7/dist-packages/visdom/server.py", line 636, in <module>
    download_scripts()
  File "/usr/local/lib/python2.7/dist-packages/visdom/server.py", line 619, in download_scripts
    logging.error('Error {} while downloading {}'.format(exc.code, key))
AttributeError: 'URLError' object has no attribute 'code'

`

**Comment by lpplbiubiubiub** [comment]
Because of GFW...

**Comment by JackUrb** [comment]
It's possible to get visdom to work despite the firewall if you're able to get the download the dependancies separately (however you can accomplish that) and then put them into folders as detailed in #174
