### ISSUE TITLE
How to run visdom on 0.0.0.0 ?

### ISSUE THREAD

**Issue by JiangPQ** [facebookresearch/visdom#213]
I would like to deploy visdom on my cloud server but cannot find a way to do so.
Is that possible for visdom?

**Comment by Seraphli** [comment]
I don't know whether you had tried to connect to your cloud server. I check the code and it actually will listen on every available interface.

**Comment by JiangPQ** [comment]
Thank you for your reply! @Seraphli 
I tried again on my server and it didn't react when running `python -m visdom.server`. After a long time it gave errors like below.
I didn't wait till it gave errors last time so I think that's why I thought visdom can't run on other interfaces.

It seems visdom is downloading its js scripts but can't fetch them.

`ubuntu@VM-72-243-ubuntu:~$ python -m visdom.server
Traceback (most recent call last):
  File "/home/ubuntu/miniconda3/lib/python3.6/urllib/request.py", line 1318, in do_open
    encode_chunked=req.has_header('Transfer-encoding'))
  File "/home/ubuntu/miniconda3/lib/python3.6/http/client.py", line 1239, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/home/ubuntu/miniconda3/lib/python3.6/http/client.py", line 1285, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/home/ubuntu/miniconda3/lib/python3.6/http/client.py", line 1234, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/home/ubuntu/miniconda3/lib/python3.6/http/client.py", line 1026, in _send_output
    self.send(msg)
  File "/home/ubuntu/miniconda3/lib/python3.6/http/client.py", line 964, in send
    self.connect()
  File "/home/ubuntu/miniconda3/lib/python3.6/http/client.py", line 1392, in connect
    super().connect()
  File "/home/ubuntu/miniconda3/lib/python3.6/http/client.py", line 936, in connect
    (self.host,self.port), self.timeout, self.source_address)
  File "/home/ubuntu/miniconda3/lib/python3.6/socket.py", line 724, in create_connection
    raise err
  File "/home/ubuntu/miniconda3/lib/python3.6/socket.py", line 713, in create_connection
    sock.connect(sa)
TimeoutError: [Errno 110] Connection timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/miniconda3/lib/python3.6/site-packages/visdom/server.py", line 669, in download_scripts
    data = opener.open(req).read()
  File "/home/ubuntu/miniconda3/lib/python3.6/urllib/request.py", line 526, in open
    response = self._open(req, data)
  File "/home/ubuntu/miniconda3/lib/python3.6/urllib/request.py", line 544, in _open
    '_open', req)
  File "/home/ubuntu/miniconda3/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/home/ubuntu/miniconda3/lib/python3.6/urllib/request.py", line 1361, in https_open
    context=self._context, check_hostname=self._check_hostname)
  File "/home/ubuntu/miniconda3/lib/python3.6/urllib/request.py", line 1320, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno 110] Connection timed out>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/miniconda3/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/ubuntu/miniconda3/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/ubuntu/miniconda3/lib/python3.6/site-packages/visdom/server.py", line 690, in <module>
    download_scripts()
  File "/home/ubuntu/miniconda3/lib/python3.6/site-packages/visdom/server.py", line 673, in download_scripts
    logging.error('Error {} while downloading {}'.format(exc.code, key))
AttributeError: 'URLError' object has no attribute 'code'`

**Comment by Seraphli** [comment]
@JiangPQ I fix that in the recent pull request, you can install the latest updated code. #224

**Comment by JiangPQ** [comment]
@Seraphli 
IT WORKS now!
Thank you!
