### ISSUE TITLE
Error starting visdom in Python 3.6

### ISSUE THREAD

**Issue by IssamLaradji** [facebookresearch/visdom#282]
Hi there!
What could be the reason for getting the following error when starting visdom ?
I am using Python 3.6. Thanks!

```
val2014: python -m visdom.server -port 1111
Downloading scripts. It might take a while.
It's Alive!
Traceback (most recent call last):
  File "/home/issam/anaconda3/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/issam/anaconda3/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/issam/anaconda3/lib/python3.6/site-packages/visdom/server.py", line 762, in <module>
    main()
  File "/home/issam/anaconda3/lib/python3.6/site-packages/visdom/server.py", line 746, in main
    app = Application()
  File "/home/issam/anaconda3/lib/python3.6/site-packages/visdom/server.py", line 126, in __init__
    f = tornado.escape.json_decode(open(p, 'r').read())
  File "/home/issam/anaconda3/lib/python3.6/site-packages/tornado/escape.py", line 87, in json_decode
    return json.loads(to_basestring(value))
  File "/home/issam/anaconda3/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/home/issam/anaconda3/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/home/issam/anaconda3/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by IssamLaradji** [comment]
Oh I just had to remove the older `.json` files for the `visdom` I was running for my older Python version -
 `Python 3.5`. Solved!

**Comment by beenazing1** [comment]
Hi,

How did you remove the older json files?
