### ISSUE TITLE
failed to establish connection

### ISSUE THREAD

**Issue by ankita-kalra** [facebookresearch/visdom#296]
Pasting the entire stack trace-
`` 
Exception in user code:
------------------------------------------------------------
Traceback (most recent call last):
  File "/home/anki/anaconda3/envs/tf/lib/python2.7/site-packages/visdom/__init__.py", line 261, in _send
    data=json.dumps(msg),
  File "/home/anki/.local/lib/python2.7/site-packages/requests/api.py", line 112, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/home/anki/.local/lib/python2.7/site-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/anki/.local/lib/python2.7/site-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/anki/.local/lib/python2.7/site-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/home/anki/.local/lib/python2.7/site-packages/requests/adapters.py", line 508, in send
    raise ConnectionError(e, request=request)
ConnectionError: HTTPConnectionPool(host='127.0.0.1', port=8957): Max retries exceeded with url: /events (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f62e27d7c90>: Failed to establish a new connection: [Errno 111] Connection refused',))
False
>>> vis.text('hw')
Exception in user code:
------------------------------------------------------------
Traceback (most recent call last):
  File "/home/anki/anaconda3/envs/tf/lib/python2.7/site-packages/visdom/__init__.py", line 261, in _send
    data=json.dumps(msg),
  File "/home/anki/.local/lib/python2.7/site-packages/requests/api.py", line 112, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/home/anki/.local/lib/python2.7/site-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/anki/.local/lib/python2.7/site-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/anki/.local/lib/python2.7/site-packages/requests/sessions.py", line 612, in send
    adapter = self.get_adapter(url=request.url)
  File "/home/anki/.local/lib/python2.7/site-packages/requests/sessions.py", line 703, in get_adapter
    raise InvalidSchema("No connection adapters were found for '%s'" % url)
InvalidSchema: No connection adapters were found for '127.0.0.1:8957/events'
False
>>> vis=visdom.Visdom(server='http://127.0.0.1',port='8957')
>>> vis.text('hw')
Exception in user code:
------------------------------------------------------------
Traceback (most recent call last):
  File "/home/anki/anaconda3/envs/tf/lib/python2.7/site-packages/visdom/__init__.py", line 261, in _send
    data=json.dumps(msg),
  File "/home/anki/.local/lib/python2.7/site-packages/requests/api.py", line 112, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/home/anki/.local/lib/python2.7/site-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/anki/.local/lib/python2.7/site-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/anki/.local/lib/python2.7/site-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/home/anki/.local/lib/python2.7/site-packages/requests/adapters.py", line 508, in send
    raise ConnectionError(e, request=request)
ConnectionError: HTTPConnectionPool(host='127.0.0.1', port=8957): Max retries exceeded with url: /events (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f62f611a290>: Failed to establish a new connection: [Errno 111] Connection refused',))

**Comment by JackUrb** [comment]
Hi @ankita-kalra, sorry you're running into an issue here - what is the output from the visdom server during these calls?

**Comment by rohitg1594** [comment]
Hi I have the issue.

**Comment by JackUrb** [comment]
Hi @rohitg1594 - If you're trying to run visdom over proxy, it's likely your issue is related to #279, and you should track the issue there. If not, please provide us with your client and server outputs from the terminal.

**Comment by rohitg1594** [comment]
Hi @JackUrb - thank you for the quick response. It was a stupid mistake on my part, I didn't start the server before training. Sorry to have wasted your time.
