### ISSUE TITLE
Error when run demo.py

### ISSUE THREAD

**Issue by lostork** [facebookresearch/visdom#306]
After install visdom as tutorial told, I run demo.py (remove the "try except" statement and run the nested code), and have the following error:

Traceback (most recent call last):
  File "/Users/mayifeng/tracking/visdom/example/demo.py", line 99, in <module>
    opts=dict(title='Random images', caption='How random.')
  File "/Users/mayifeng/tracking/.env/lib/python2.7/site-packages/visdom-0.1.7.2-py2.7.egg/visdom/__init__.py", line 230, in result
    return fn(*args, **kwargs)
  File "/Users/mayifeng/tracking/.env/lib/python2.7/site-packages/visdom-0.1.7.2-py2.7.egg/visdom/__init__.py", line 601, in images
    grid = np.ones([3, height * ymaps, width * xmaps])
  File "/Users/mayifeng/tracking/.env/lib/python2.7/site-packages/numpy/core/numeric.py", line 192, in ones
    a = empty(shape, dtype, order)
TypeError: 'tuple' object cannot be interpreted as an index 

I check the /visdom/__init__.py and find:
`
        nmaps = tensor.shape[0]
        xmaps = min(nrow, nmaps)
        ymaps = int(math.ceil(float(nmaps) / xmaps))
        height = int(tensor.shape[2] + 2 * padding),
        width = int(tensor.shape[3] + 2 * padding)

        grid = np.ones([3, height * ymaps, width * xmaps])
`

I think that the comma at the end of the 4th line is the problem. I remove it and the demo.py run successfully.

I check the history of this __init__.py on GitHub.I find out in one history version the code block is like this:
`
        nmaps = tensor.shape[0]
        xmaps = min(nrow, nmaps)
        ymaps = int(math.ceil(float(nmaps) / xmaps))
        height, width = int(tensor.shape[2] + 2 * padding), int(tensor.shape[3] + 2 * padding)

        grid = np.ones([3, height * ymaps, width * xmaps])
`

I guess the comma is a bug after refactoring the code.
Sorry for my poor English. I hope my comment is clear...

**Comment by JackUrb** [comment]
Definitely a bug, fixing now. Thanks for the catch!
