### ISSUE TITLE
'Visdom' object has no attribute 'updateTrace'

### ISSUE THREAD

**Issue by Luckick** [facebookresearch/visdom#358]
Hi, 
I got a problem when using visdom, the version is the most recent.
Python 3.6.5 |Anaconda custom (64-bit)| (default, Apr 29 2018, 16:14:56) 
[GCC 7.2.0] on linux

>>> visdom.__version__
'0.1.8.3'

$ python capsule_network.py
# parameters: 8215568
100%|█████████████████████████████████████████| 600/600 [09:01<00:00,  1.11it/s]
[Epoch 1] Training Loss: 0.5196 (Accuracy: 89.01%)
Traceback (most recent call last):
  File "capsule_network.py", line 287, in <module>
    engine.train(processor, get_iterator(True), maxepoch=NUM_EPOCHS, optimizer=optimizer)
  File "/opt/anaconda3/lib/python3.6/site-packages/torchnet-0.0.2-py3.6.egg/torchnet/engine/engine.py", line 67, in train
  File "/opt/anaconda3/lib/python3.6/site-packages/torchnet-0.0.2-py3.6.egg/torchnet/engine/engine.py", line 31, in hook
  File "capsule_network.py", line 250, in on_end_epoch
    train_loss_logger.log(state['epoch'], meter_loss.value()[0])
  File "/opt/anaconda3/lib/python3.6/site-packages/torchnet-0.0.2-py3.6.egg/torchnet/logger/visdomlogger.py", line 159, in log
  File "/opt/anaconda3/lib/python3.6/site-packages/torchnet-0.0.2-py3.6.egg/torchnet/logger/visdomlogger.py", line 139, in log
AttributeError: 'Visdom' object has no attribute 'updateTrace'

**Comment by lvdmaaten** [comment]
The `updateTrace` function was deprecated over six months ago, and was removed in https://github.com/facebookresearch/visdom/commit/5e1a28f740741ad265beb9fff00127631fbe6e11

Please open an issue in https://github.com/pytorch/tnt
