### ISSUE TITLE
Visdom server offline

### ISSUE THREAD

**Issue by TommeyChang** [facebookresearch/visdom#398]
ENV: ubuntu 16.04 with python 3.5
Vidsom installed: sorce code

Problem description:
My visdom server could be setup correctly, and my programme could connect to it either. However, when I try to watch the results in the chrome with url http://localhost:8097. I can connect to the server, but there is nothing, and the work state is offline. Meanwhile, the terminal output the infomation as below. 
I tried to fix the problem by updating the tornado, but I did not work.

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/tornado/http1connection.py", line 237, in _read_message
    delegate.finish()
  File "/usr/local/lib/python3.5/dist-packages/tornado/routing.py", line 256, in finish
    self.delegate.finish()
  File "/usr/local/lib/python3.5/dist-packages/tornado/web.py", line 2139, in finish
    self.execute()
  File "/usr/local/lib/python3.5/dist-packages/tornado/web.py", line 2159, in execute
    **self.handler_kwargs)
  File "/usr/local/lib/python3.5/dist-packages/tornado/websocket.py", line 141, in __init__
    super(WebSocketHandler, self).__init__(application, request, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/tornado/web.py", line 193, in __init__
    self.initialize(**kwargs)
  File "/usr/local/lib/python3.5/dist-packages/visdom-0.1.8.3-py3.5.egg/visdom/server.py", line 218, in initialize
    self.layouts = self.load_layouts()
  File "/usr/local/lib/python3.5/dist-packages/visdom-0.1.8.3-py3.5.egg/visdom/server.py", line 243, in load_layouts
    ensure_dir_exists(layout_filepath)
  File "/usr/local/lib/python3.5/dist-packages/visdom-0.1.8.3-py3.5.egg/visdom/server.py", line 53, in ensure_dir_exists
    assert e1.errno == 17  # errno.EEXIST
AssertionError

**Comment by JackUrb** [comment]
Are you running with proxies? Have you followed the download script instructions in https://github.com/facebookresearch/visdom/blob/master/CONTRIBUTING.md

**Comment by TommeyChang** [comment]
Yes, I set the ssh and run the ufw command

**Comment by JackUrb** [comment]
That's supposed to be the error number for a file/directory not existing, however for some reason on your machine a different error is happening. Perhaps it has to do with restricted access? Try either running as a super user or adding a print to that `ensure_dir_exists` call so that you can see what folder it's trying to create and then create it yourself.

**Comment by JackUrb** [comment]
Closing as inactive - please feel free to reopen this issue with more details if you're still having this problem.
