### ISSUE TITLE
Permission Denied for unexisting folder

### ISSUE THREAD

**Issue by rafaelvalle** [facebookresearch/visdom#408]
Hi All.

On Python 2.7.12 and visdom 0.1.8.3, when executing python -m visdom.server I get:
```
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/local/lib/python2.7/dist-packages/visdom/server.py", line 1062, in <module>
    download_scripts()
  File "/usr/local/lib/python2.7/dist-packages/visdom/server.py", line 964, in download_scripts
    os.makedirs(directory)
  File "/usr/lib/python2.7/os.py", line 157, in makedirs
    mkdir(name, mode)
OSError: [Errno 13] Permission denied: '/usr/local/lib/python2.7/dist-packages/visdom/static/fonts'
```

The folder `/usr/local/lib/python2.7/dist-packages/visdom/static/` does exist but it's children `fonts` does not.

**Comment by JackUrb** [comment]
Try running the `download.sh` script and seeing if this resolves the issue. It's possible that permissions are preventing the fonts directory from being created, so you may need to run it with whatever user access is required to create the relevant directories.

**Comment by rafaelvalle** [comment]
It's unlikely that its permissions because the css and other folders are there.
I'm trying to install in a docker container.
When do you suggest running `download.sh` and what do you suggest doing after that?

**Comment by rafaelvalle** [comment]
I see. When running `python -m visdom.server`, how does one points the server to the downloaded files? 

I'm also facing a `Connection Refused` error while trying to write images or text. Let me know if you want me to open a separate issue for it.

**Comment by JackUrb** [comment]
@rafaelvalle any updates here?

**Comment by sbutcher** [comment]
I was getting a permission denied error when running this in a container due to some errors in the download.sh script. I have submitted PR #485 to resolve this.
