### ISSUE TITLE
[Feature Request] Be able to retrieve list of all envs on server

### ISSUE THREAD

**Issue by sbaio** [facebookresearch/visdom#445]
Hi !

Can we have a function (vis.all_envs) to retrieve all envs on server in order to filter environments by name/id ?

Thank you

**Comment by JackUrb** [comment]
This was implemented in #463

**Comment by dizcza** [comment]
Hi, I was looking for env list too. I run 
`pip install --upgrade git+https://github.com/facebookresearch/visdom.git`
and then

```
viz.get_env_list()

Traceback (most recent call last):
  File "/home/dizcza/anaconda3/envs/embsdr_cpu/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 2961, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-4-9aba7c600f13>", line 1, in <module>
    viz.get_env_list()
  File "/home/dizcza/anaconda3/envs/embsdr_cpu/lib/python3.6/site-packages/visdom/__init__.py", line 577, in get_env_list
    return json.loads(self._send({}, endpoint='env_state', quiet=True))
  File "/home/dizcza/anaconda3/envs/embsdr_cpu/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/home/dizcza/anaconda3/envs/embsdr_cpu/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/home/dizcza/anaconda3/envs/embsdr_cpu/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by dizcza** [comment]
Sorry, I forgot to kill other (old) visdom servers, running on my system with different ports and permissions. Now it works fine.
