### ISSUE TITLE
The Python example is not running

### ISSUE THREAD

**Issue by JafferWilson** [facebookresearch/visdom#549]
**Bug Description**
I have copied the example from the repository. I copied te python program and try to run it with `python visdom_example.py`. And I received the error where connection failed.

**Reproduction Steps**
Enter steps to reproduce the behavior:

**Expected behavior**
The program must run on given server.
**Screenshots**
A console log is available. No snapshot.

**Client logs:**
```
python visdom_example.py
WARNING:root:Setting up a new session...
Exception in user code:
------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Python35\lib\site-packages\urllib3\connection.py", line 141, in _new_conn
    (self.host, self.port), self.timeout, **extra_kw)
  File "C:\Python35\lib\site-packages\urllib3\util\connection.py", line 83, in create_connection
    raise err
  File "C:\Python35\lib\site-packages\urllib3\util\connection.py", line 73, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [WinError 10061] No connection could be made because the target machine actively refused it

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Python35\lib\site-packages\urllib3\connectionpool.py", line 601, in urlopen
    chunked=chunked)
  File "C:\Python35\lib\site-packages\urllib3\connectionpool.py", line 357, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "C:\Python35\lib\http\client.py", line 1083, in request
    self._send_request(method, url, body, headers)
  File "C:\Python35\lib\http\client.py", line 1128, in _send_request
    self.endheaders(body)
  File "C:\Python35\lib\http\client.py", line 1079, in endheaders
    self._send_output(message_body)
  File "C:\Python35\lib\http\client.py", line 911, in _send_output
    self.send(msg)
  File "C:\Python35\lib\http\client.py", line 854, in send
    self.connect()
  File "C:\Python35\lib\site-packages\urllib3\connection.py", line 166, in connect
    conn = self._new_conn()
  File "C:\Python35\lib\site-packages\urllib3\connection.py", line 150, in _new_conn
    self, "Failed to establish a new connection: %s" % e)
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x000002251DFBFB70>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Python35\lib\site-packages\requests\adapters.py", line 440, in send
    timeout=timeout
  File "C:\Python35\lib\site-packages\urllib3\connectionpool.py", line 639, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "C:\Python35\lib\site-packages\urllib3\util\retry.py", line 388, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=8097): Max retries exceeded with url: /env/main (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002251DFBFB70>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Python35\lib\site-packages\visdom\__init__.py", line 548, in _send
    data=json.dumps(msg),
  File "C:\Python35\lib\site-packages\requests\sessions.py", line 555, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "C:\Python35\lib\site-packages\requests\sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Python35\lib\site-packages\requests\sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "C:\Python35\lib\site-packages\requests\adapters.py", line 508, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=8097): Max retries exceeded with url: /env/main (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002251DFBFB70>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',))
ERROR:visdom:[WinError 10061] No connection could be made because the target machine actively refused it
waiting
waiting
waiting
waiting
waiting
waiting
waiting
waiting
waiting
waiting
waiting
waiting
waiting
waiting
waiting
waiting
waiting
waiting
waiting
waiting
waiting
waiting
waiting
waiting
waiting
waiting
waiting
waiting
waiting
waiting
The visdom experienced an exception while running: AssertionError('No connection could be formed quickly',)
The demo displays up-to-date functionality with the GitHub version, which may not yet be pushed to pip. Please upgrade using `pip install -e .` or `easy_install .`
If this does not resolve the problem, please open an issue on our GitHub.
```

**Server logs:**
No server log yet as the application didn't worked.

**Additional context**
Python version===> Python 3.5.0
Pip version ==> pip 18.1 from c:\python35\lib\site-packages\pip (python 3.5)
visdom version ==> '0.1.8.7'
OS ==> Window 10 Home
Windows version ====> 10
Websocket library version ===> '0.47.0'

**Comment by vfdev-5** [comment]
@JafferWilson did you run the server in another terminal ? Something like this
```
> visdom 
# or 
> python -m visdom.server
```
as described in the [usage](https://github.com/facebookresearch/visdom#usage)

HTH

**Comment by fermat97** [comment]
I have more or less the same problem. Running the demo I get this error:

> WARNING:root:Setting up a new session...
ERROR:visdom:[Errno -2] Name or service not known
ERROR:visdom:[Errno -2] Name or service not known
ERROR:visdom:[Errno -2] Name or service not known
WARNING:visdom:Visdom python client failed to establish socket to get messages from the server. This feature is optional and can be disabled by initializing Visdom with `use_incoming_socket=False`, which will prevent waiting for this request to timeout.
waiting
waiting
waiting
waiting
waiting
waiting
waiting
waiting
waiting
waiting
waiting
waiting
waiting
waiting
waiting
waiting
waiting
waiting
waiting
waiting
waiting
waiting
waiting
waiting
waiting
ERROR:visdom:[Errno -2] Name or service not known
waiting
waiting
waiting
waiting
waiting
The visdom experienced an exception while running: AssertionError('No connection could be formed quickly',)
The demo displays up-to-date functionality with the GitHub version, which may not yet be pushed to pip. Please upgrade using `pip install -e .` or `easy_install .`
If this does not resolve the problem, please open an issue on our GitHub.

The connection is active on another terminal and the blue page is appeared in my browser.  Do you have any idea?

**Comment by JackUrb** [comment]
Can you try creating a visdom instance within a python session manually and fill the `hostname` and `port` arguments manually?
