### ISSUE TITLE
Visdom hanging on connect

### ISSUE THREAD

**Issue by rdevon** [facebookresearch/visdom#560]
I'm having issues with connecting to my visdom server with *some* experiments. Note, this only happens with some of my larger experiments, but it isn't even consistent as this occurs after long periods of things working fine.

What happens is that visdom hangs and I cannot plot. The values being sent to the visdom server are not larger, usually nothing more than a dozen 2x2 matrices. If I do a keyboard interrupt, I get:

```
Traceback (most recent call last):
  File "scripts/deep_infomax.py", line 68, in <module>
    run(controller)
  File "/home/devonh/.local/lib/python3.7/site-packages/cortex/main.py", line 48, in run
    train.main_loop(model, **exp.ARGS['train'])
  File "/home/devonh/.local/lib/python3.7/site-packages/cortex/_lib/train.py", line 415, in main_loop
    plot(epoch, init=(epoch == first_epoch), viz_test_only=viz_test_only)
  File "/home/devonh/.local/lib/python3.7/site-packages/cortex/_lib/viz.py", line 276, in plot
    update=update
  File "/home/devonh/.local/lib/python3.7/site-packages/visdom/__init__.py", line 335, in wrapped_f
    return f(*args, **kwargs)
  File "/home/devonh/.local/lib/python3.7/site-packages/visdom/__init__.py", line 1367, in line
    update=update, name=name)
  File "/home/devonh/.local/lib/python3.7/site-packages/visdom/__init__.py", line 335, in wrapped_f
    return f(*args, **kwargs)
  File "/home/devonh/.local/lib/python3.7/site-packages/visdom/__init__.py", line 1292, in scatter
    return self._send(data_to_send, endpoint=endpoint)
  File "/home/devonh/.local/lib/python3.7/site-packages/visdom/__init__.py", line 548, in _send
    data=json.dumps(msg),
  File "/home/devonh/.local/lib/python3.7/site-packages/requests/sessions.py", line 581, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/home/devonh/.local/lib/python3.7/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/devonh/.local/lib/python3.7/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/home/devonh/.local/lib/python3.7/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/home/devonh/.local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/home/devonh/.local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 380, in _make_request
    httplib_response = conn.getresponse()
  File "/home/devonh/anaconda3/lib/python3.7/http/client.py", line 1321, in getresponse
    response.begin()
  File "/home/devonh/anaconda3/lib/python3.7/http/client.py", line 296, in begin
    version, status, reason = self._read_status()
  File "/home/devonh/anaconda3/lib/python3.7/http/client.py", line 257, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/home/devonh/anaconda3/lib/python3.7/socket.py", line 589, in readinto
    return self._sock.recv_into(b)
KeyboardInterrupt
```

This is after a few-minute hang.

Any way to fix this? I am using version 0.1.8.8

**Comment by JackUrb** [comment]
Hi @rdevon - Is it localized to any particular kind of operation (such as an append vs new plot, etc.)? Are you updating large amounts of data? Does this only happen if you are actively monitoring the dashboard? I'm thinking it might be related to #552 somehow, in which case the server logs would be more interesting at the moment of hanging.

**Comment by rdevon** [comment]
Here are the relevant lines of code:

```
        opts = dict(
            xlabel='epochs',
            legend=legend,
            ylabel=k,
            title=k)

        X = np.array(X).transpose()
        Y = np.array(Y).transpose()

        if init:
            update = None
        else:
            update = 'append'

        visualizer.line(
            Y=Y,
            X=X,
            env=exp.NAME,
            opts=opts,
            win='line_{}'.format(k),
            update=update
        )
```

here, `exp.NAME` is a string, `k` also a string, `X` and `Y` are small arrays (max 2x2). I've tried hacking update as `None` or `"append"` but same behavior.
Strangely if I reduce the batch size, this can sometimes help, despite none of the arrays being passed to visdom changing size: perhaps this is related to RAM usage?

**Comment by JackUrb** [comment]
It's almost definitely hanging on the server side - can you get logs of what happens if you try to kill the server when this is happening?

**Comment by rdevon** [comment]
If I kill the server?

```
ERROR:visdom:Connection is already closed.
ERROR:visdom:[Errno 111] Connection refused
ERROR:visdom:[Errno 111] Connection refused
ERROR:visdom:[Errno 111] Connection refused
ERROR:visdom:[Errno 111] Connection refused
ERROR:visdom:[Errno 111] Connection refused
```

**Comment by JackUrb** [comment]
I'm referring to the server logs from killing during a hang. Killing it should interrupt the io loop that it's hanging on, and surface where it might be caught

**Comment by rdevon** [comment]
So if I wait long enough, I get this error client-side:

```
Traceback (most recent call last):
  File "/home/devonh/.local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 384, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/home/devonh/.local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 380, in _make_request
    httplib_response = conn.getresponse()
  File "/home/devonh/anaconda3/lib/python3.7/http/client.py", line 1321, in getresponse
    response.begin()
  File "/home/devonh/anaconda3/lib/python3.7/http/client.py", line 296, in begin
    version, status, reason = self._read_status()
  File "/home/devonh/anaconda3/lib/python3.7/http/client.py", line 257, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/home/devonh/anaconda3/lib/python3.7/socket.py", line 589, in readinto
    return self._sock.recv_into(b)
TimeoutError: [Errno 110] Connection timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/devonh/.local/lib/python3.7/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/home/devonh/.local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/home/devonh/.local/lib/python3.7/site-packages/urllib3/util/retry.py", line 367, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/home/devonh/.local/lib/python3.7/site-packages/urllib3/packages/six.py", line 686, in reraise
    raise value
  File "/home/devonh/.local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/home/devonh/.local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 386, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "/home/devonh/.local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 317, in _raise_timeout
    raise ReadTimeoutError(self, url, "Read timed out. (read timeout=%s)" % timeout_value)
urllib3.exceptions.ReadTimeoutError: HTTPConnectionPool(host='40.117.235.91', port=80): Read timed out. (read timeout=None)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/devonh/.local/lib/python3.7/site-packages/visdom/__init__.py", line 548, in _send
    data=json.dumps(msg),
  File "/home/devonh/.local/lib/python3.7/site-packages/requests/sessions.py", line 581, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/home/devonh/.local/lib/python3.7/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/devonh/.local/lib/python3.7/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/home/devonh/.local/lib/python3.7/site-packages/requests/adapters.py", line 529, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPConnectionPool(host='40.117.235.91', port=80): Read timed out. (read timeout=None)
```

**Comment by rdevon** [comment]
Server side:
```
ERROR:root:ERROR: 405: {'exc_info': (<class 'tornado.web.HTTPError'>, HTTPError(), <traceback object at 0x7f657d964208>)}
WARNING:tornado.access:405 HEAD / (5.189.188.237) 0.85ms
```

**Comment by JackUrb** [comment]
Ack I must have the server logging improperly set up - the traceback at `<traceback object at 0x7f657d964208>` would likely contain the correct debug info.

**Comment by rdevon** [comment]
OK, let me know what I can do next. I suppose I could go as far as add a print in the sitepackage source for visdom.

**Comment by JackUrb** [comment]
@rdevon that would be extremely helpful! Unfortunately my bandwidth at the moment is extremely restricted and I doubt I'd get to dig into this until sometime next week.

**Comment by JackUrb** [comment]
Hi @rdevon I'm finally looping back into visdom issues, were you ever able to see where this was happening? I'm introducing the relevant logging in #585 in case you haven't yet.

**Comment by rdevon** [comment]
Sorry I missed this, I'm doing some testing now. The logging should be on the server side right? Anything special I need to do to ensure the logs show up?

**Comment by JackUrb** [comment]
Only requirement is to be running from the most recent master, otherwise they should show up now.

**Comment by rdevon** [comment]
One the server or client side (or both)?

**Comment by rdevon** [comment]
After installing master from source and starting the server back up, no error was returned after the client threw the error ending with `requests.exceptions.ReadTimeout: HTTPConnectionPool(host=<IP>, port=80): Read timed out. (read timeout=None)` after waiting some time.

**Comment by rdevon** [comment]
I think this *might* have something to do with the time between updates for visdom. If the model goes through an epoch quickly, there's no problem, but if it takes minutes to send updates from the client to the server, then it hangs.

**Comment by JackUrb** [comment]
Odd, the server-side should've logged the same kind of `ERROR:root:ERROR: 405...` line it had in the past, but with additional details following. 

The difference in time between submissions is an interesting note though - also odd that the issue is a ReadTimeout. I'd be curious if the last update ended up rendering on the frontend before the crash, because if so I might need to investigate retry logic and unique request ids next.

**Comment by rdevon** [comment]
So I can confirm hanging goes away if I simply push dummy data (i.e., text) to the server every model update. I'm sure less is necessary, but whatever configuration my server is running on seems unamenable to long update times.

**Comment by JackUrb** [comment]
@rdevon With that confirmation I suspect it has to do with our use of a request session. A real fix would be to catch the timeout specifically (first by explicitly setting a shorter timeout on the `_send` call so that it doesn't hang for an unacceptable amount of time), then attempt to refresh the visdom object's `_session` object and retry on a failure. Thanks for your work investigating so far.
