### ISSUE TITLE
vis.video with OpenCV 4

### ISSUE THREAD

**Issue by ohwi** [facebookresearch/visdom#569]
**Bug Description**

vis.video throws UnboundLocalError with OpenCV version 4:

```{python}
Traceback (most recent call last):
  File "/Users/ohwi/Practice/visdom/samples/06_1. etc.py", line 24, in <module>
    title="Alohomora",
  File "/anaconda3/lib/python3.7/site-packages/visdom/__init__.py", line 335, in wrapped_f
    return f(*args, **kwargs)
  File "/anaconda3/lib/python3.7/site-packages/visdom/__init__.py", line 1064, in video
    fourcc,
UnboundLocalError: local variable 'fourcc' referenced before assignment
```

**Reproduction Steps**

```{python}
vid = cv2.VideoCapture("assets/Alohomora.mp4")
	frames = []
	while True:
		ret, frame = vid.read()
		if not ret:
			vid.release()
			break
		frames.append(frame)

	vis.video(
		np.array(frames),
		opts=dict(
			title="Alohomora",
		)
	)
```

**Expected behavior**

Visdom writes video.

I think ```elif cv2.__version__.startswith(('3', '4')):``` at line 1055 of \_\_init\_\_.py may solve the problem.

**Comment by JackUrb** [comment]
Ah we haven't been doing a good job keeping up on visdom's video implementation at the moment. If adding the given line solves the problem for you, feel free to open a PR with it!
