### ISSUE TITLE
Mokeypatching visdom

### ISSUE THREAD

**Issue by episodeyang** [facebookresearch/visdom#62]
Hi,

I'm trying to patch visdom to take in a `name` variable on instantiation, but I keep getting an error. This is probably a stupid question, but what is the proper way to do this?

```python
class Dashboard(Visdom):
    def __init_(self, name):
        super(Dashboard, self).__init__()
        self.env = name
```

```error
Traceback (most recent call last):
  File "/home/user/anaconda3/envs/deep-learning/lib/python3.6/site-packages/visdom/__init__.py", line 220, in _send
    data=json.dumps(msg),
  File "/home/user/anaconda3/envs/deep-learning/lib/python3.6/site-packages/requests/api.py", line 110, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/home/user/anaconda3/envs/deep-learning/lib/python3.6/site-packages/requests/api.py", line 56, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/user/anaconda3/envs/deep-learning/lib/python3.6/site-packages/requests/sessions.py", line 488, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/user/anaconda3/envs/deep-learning/lib/python3.6/site-packages/requests/sessions.py", line 603, in send
    adapter = self.get_adapter(url=request.url)
  File "/home/user/anaconda3/envs/deep-learning/lib/python3.6/site-packages/requests/sessions.py", line 685, in get_adapter
    raise InvalidSchema("No connection adapters were found for '%s'" % url)
requests.exceptions.InvalidSchema: No connection adapters were found for 'seq-to-seq-experiment:8097/events'
```

**Comment by episodeyang** [comment]
Ha, I missed an underscore in the function name.
