### ISSUE TITLE
TypeError: 'module' object is not callable

### ISSUE THREAD

**Issue by Captainzj** [facebookresearch/visdom#625]
```
Traceback (most recent call last):
  File "...generate_acc_loss_plot.py", line 208, in <module>
    visualize_sample('some')
  File "...generate_acc_loss_plot.py", line 183, in visualize_sample
    vis = Vis(env=env_name)
TypeError: 'module' object is not callable
```

**Comment by JackUrb** [comment]
Please view the docs or the demo. The syntax is `vis = visdom.Visdom()`
