### ISSUE TITLE
No module named 'jsonpatch' after upgrading visdom to version 0.1.8.9

### ISSUE THREAD

**Issue by pebauer** [facebookresearch/visdom#679]
I just upgraded visdom within the anaconda environment from version 0.1.8.8 to version 0.1.8.9 on MacOS 10.15 (Catalina). Hint: Visdom 0.1.8.8 worked without any issues on MacOS 10.15.

Visdom version 0.1.8.9 does not work when I run the terminal command:
"python3 -m visdom.server"

I get the following error...

Traceback (most recent call last):
  File "/Users/MY_USERNAME/anaconda3/envs/MY_ENVIRONMENT/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/Users/MY_USERNAME/anaconda3/envs/MY_ENVIRONMENT/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/MY_USERNAME/anaconda3/MY_ENVIRONMENT/MA_369/lib/python3.6/site-packages/visdom/server.py", line 20, in <module>
    import jsonpatch
ModuleNotFoundError: No module named 'jsonpatch'

**Comment by pebauer** [comment]
I found the solution.

I had to additionally install the "Jsonpatch" library in the anaconda environment.
(see: https://anaconda.org/conda-forge/jsonpatch)

After that I was able to run "python3 -m visdom.server" (without any errors resp. problems)
