### ISSUE TITLE
Matplot Resizable=True not working

### ISSUE THREAD

**Issue by JafferWilson** [facebookresearch/visdom#709]
**Bug Description**
I am trying to plot Matplotlib PLot in the visdom. But there is issue with resizable=True.

**Reproduction Steps**
```
>>> import visdom
>>> viz = visdom.Visdom()
Setting up a new session...
>>> import matplotlib.pyplot as plt
>>> plt.plot([1, 23, 2, 4])
[<matplotlib.lines.Line2D object at 0x00000277EC0E1D30>]
>>> plt.ylabel('some numbers')
Text(0,0.5,'some numbers')
>>> viz.matplot(plt,opts=dict(resizable=True))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python35\lib\site-packages\visdom\__init__.py", line 1028, in matplot
    opts['height'] = 1.4 * int(math.ceil(float(height)))
ValueError: could not convert string to float: '345.6pt'
```

**Expected behavior**
Plotting the matplot in Visdom

**Client logs:**
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python35\lib\site-packages\visdom\__init__.py", line 1028, in matplot
    opts['height'] = 1.4 * int(math.ceil(float(height)))
ValueError: could not convert string to float: '345.6pt'
```

**Server logs:**
```
INFO:root:Opened visdom socket from ip: ::1
INFO:tornado.access:200 POST /events (127.0.0.1) 4.99ms
```
**Additional Information:**
```
visdom version: '0.1.8.9'
Python version: 3.5.0
Windows version: 10
matplotlib version: 2.2.2
```

**Comment by Romain3Ch216** [comment]
Hi @JafferWilson 

I have the same problem, did you solve it ?
