### ISSUE TITLE
Exception in user code

### ISSUE THREAD

**Issue by MasonZong** [facebookresearch/visdom#754]
# Description

I run visdom server (python -m visdom.server)on Ubuntu. 
There is something wrong when I excute python demo:

```
import visdom
import numpy as np
vis = visdom.Visdom()
vis.text('Hello, world!')
vis.image(np.ones((3, 10, 10)))
```

# error message

```python
WARNING:root:Setting up a new session...
Exception in user code:
------------------------------------------------------------
Traceback (most recent call last):
  File "/home/eini/anaconda3/lib/python3.7/site-packages/urllib3/connection.py", line 157, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw
  File "/home/eini/anaconda3/lib/python3.7/site-packages/urllib3/util/connection.py", line 84, in create_connection
    raise err
  File "/home/eini/anaconda3/lib/python3.7/site-packages/urllib3/util/connection.py", line 74, in create_connection
    sock.connect(sa)
TimeoutError: [Errno 110] Connection timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 ......
  File "/home/eini/anaconda3/lib/python3.7/site-packages/urllib3/connection.py", line 169, in _new_conn
    self, "Failed to establish a new connection: %s" % e
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7f9669ccd450>: Failed to establish a new connection: [Errno 110] Connection timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
......
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='172.23.15.175', port=808): Max retries exceeded with url: http://localhost:8097/env/main (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9669ccd450>: Failed to establish a new connection: [Errno 110] Connection timed out')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/eini/anaconda3/lib/python3.7/site-packages/visdom/__init__.py", line 548, in _send
    data=json.dumps(msg),
......
requests.exceptions.ProxyError: HTTPConnectionPool(host='172.23.15.175', port=808): Max retries exceeded with url: http://localhost:8097/env/main (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9669ccd450>: Failed to establish a new connection: [Errno 110] Connection timed out')))
WARNING:visdom:Visdom python client failed to establish socket to get messages from the server. This feature is optional and can be disabled by initializing Visdom with `use_incoming_socket=False`, which will prevent waiting for this request to timeout.
ERROR:visdom:[Errno 110] Connection timed out
Exception in user code:
------------------------------------------------------------
Traceback (most recent call last):
  File "/home/eini/anaconda3/lib/python3.7/site-packages/urllib3/connection.py", line 157, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw
  File "/home/eini/anaconda3/lib/python3.7/site-packages/urllib3/util/connection.py", line 84, in create_connection
    raise err
  File "/home/eini/anaconda3/lib/python3.7/site-packages/urllib3/util/connection.py", line 74, in create_connection
    sock.connect(sa)
TimeoutError: [Errno 110] Connection timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
......
  File "/home/eini/anaconda3/lib/python3.7/site-packages/urllib3/connection.py", line 169, in _new_conn
    self, "Failed to establish a new connection: %s" % e
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7f9669c43c50>: Failed to establish a new connection: [Errno 110] Connection timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
......
  File "/home/eini/anaconda3/lib/python3.7/site-packages/urllib3/util/retry.py", line 436, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='172.23.15.175', port=808): Max retries exceeded with url: http://localhost:8097/events (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9669c43c50>: Failed to establish a new connection: [Errno 110] Connection timed out')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
......
requests.exceptions.ProxyError: HTTPConnectionPool(host='172.23.15.175', port=808): Max retries exceeded with url: http://localhost:8097/events (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9669c43c50>: Failed to establish a new connection: [Errno 110] Connection timed out')))

```

I have tried to Modify demo like:  but it doesn't work。
```
vis = visdom.Visdom(se_incoming_socket=False) 
```

**Comment by Kimia770109** [comment]
Excuse me! Did you find any solution for this error?

**Comment by da-h** [comment]
Hey there,

it seems that the server cannot be reached.

Could you please provide more information on your config, e.g. how did you start visdom, how did you initialize the python `Visdom`-object? Are there special things to consider for bug searching, like a reverse-proxy?

Also, there has been recently an update of the conda package.
Please make sure to run the most recent `0.2.4` version to make bug hunting easier.

Best
*da-h*

**Comment by Kimia770109** [comment]
> 

actually, I'm not really a pro in python, for my project, have to use visdom. I'm coding in colab and use this code:

`import visdom
vis = visdom.Visdom(server ='python -m visdom.server', port=opt.display_port)
vis.images(images, nrow=ncols, win=self.display_id + 1, padding=2, opts=dict(title=title + ' images'))
`

but I get these errors and I can't understand what's the real problem is.

````
ERROR:visdom:[Errno -2] Name or service not known
ERROR:websocket:[Errno -2] Name or service not known - goodbye
ERROR:websocket:error from callback <function Visdom.setup_socket.<locals>.on_close at 0x7ff5d6815af0>: on_close() takes 1 positional argument but 3 were given
ERROR:visdom:on_close() takes 1 positional argument but 3 were given
WARNING:visdom:Visdom python client failed to establish socket to get messages from the server. This feature is optional and can be disabled by initializing Visdom with use_incoming_socket=False`, which will prevent waiting for this request to timeout.
create web directory ./checkpoints/experiment_name/web..'
```

**Comment by rajnisht7** [comment]
Closing this issue as it doesn't exist anymore.Thank You
