### ISSUE TITLE
Error when runnning visdom: The 'torchfile' distribution was not found and is required by visdom

### ISSUE THREAD

**Issue by Jimmy2027** [facebookresearch/visdom#760]
**Bug Description**
Hello, after I install visdom, I get the following error when I run the command `visdom` in the terminal:

```
Traceback (most recent call last):
  File "/usr/lib/python-exec/python3.6/visdom", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib64/python3.6/site-packages/pkg_resources/__init__.py", line 3251, in <module>
    @_call_aside
  File "/usr/lib64/python3.6/site-packages/pkg_resources/__init__.py", line 3235, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib64/python3.6/site-packages/pkg_resources/__init__.py", line 3264, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib64/python3.6/site-packages/pkg_resources/__init__.py", line 583, in _build_master
    ws.require(__requires__)
  File "/usr/lib64/python3.6/site-packages/pkg_resources/__init__.py", line 900, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib64/python3.6/site-packages/pkg_resources/__init__.py", line 786, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'torchfile' distribution was not found and is required by visdom
```

Where can I find the needed package? I don't see it anywhere in the requirements for visdom nor anywhere else in the source code.

**Comment by JackUrb** [comment]
Ah the reference to this requirement can likely be removed, we deprecated torch support over a year ago and `torchfile` is a remnant of that functionality.

**Comment by Jimmy2027** [comment]
Hi @JackUrb, thanks for your response! Is there any way I can get rid of this error then? I don't find the code where visdom is looking for torchfile :/

**Comment by JackUrb** [comment]
What version of visdom are you running here? Indeed `torchfile` has been removed from the repo, so it seems you're somehow on an earlier revision?

**Comment by Manik-Khajuria-5** [comment]
torchfile is no longer referenced anywhere in the codebase
